version: "3"

vars:
  ENVOY_CONTAINER_NAME: dev.boardsbe.envoy
  YQ: docker run -i --rm -v .:/boardsbe mikefarah/yq

tasks:
  dev.env:
    cmds:
      - task: dev.env.envoy
      - cmd: echo "dev env started. run 'task dev.env.stop' to stop"

  dev.env.stop:
    cmds:
      - task: dev.env.envoy.stop

  dev.env.envoy:
    vars:
      DOCKER_IMAGE: envoyproxy/envoy:v1.28-latest
      PUBLISH_PORT:
        sh: "{{.YQ}} '.dev.envoy_docker.publish_port' /boardsbe/config/dev.yaml"
      DOCKER_PORT:
        sh: "{{.YQ}} '.dev.envoy_docker.docker_port' /boardsbe/config/dev.yaml"
      GRPC_SERVER_PORT:
        sh: "{{.YQ}} '.grpc_server.port' /boardsbe/config/dev.yaml"
    cmds:
      - cp config/envoy.dev.example.yaml config/envoy.dev.yaml
      - "{{.YQ}} --inplace '.static_resources.listeners[0].address.socket_address.port_value = {{.DOCKER_PORT}}' /boardsbe/config/envoy.dev.yaml"
      - "{{.YQ}} --inplace '.static_resources.clusters[0].load_assignment.endpoints[0].lb_endpoints[0].endpoint.address.socket_address.port_value = {{.GRPC_SERVER_PORT}}' /boardsbe/config/envoy.dev.yaml"
      - docker run --rm -d --name {{.ENVOY_CONTAINER_NAME}} -v ./config/envoy.dev.yaml:/etc/envoy/envoy.yaml -p {{.PUBLISH_PORT}}:{{.DOCKER_PORT}} -e ENVOY_UID=$(id -u) {{.DOCKER_IMAGE}}

  dev.env.envoy.stop:
    cmd: docker stop {{.ENVOY_CONTAINER_NAME}}

  dev.proto.update:
    vars:
      LATEST_COMMIT:
        sh: curl -s "https://api.github.com/repos/anyboards/proto/commits" | {{.YQ}} -r '.[0].sha'
    cmd: go get github.com/anyboards/proto@{{.LATEST_COMMIT}}

  grpcui:
    vars:
      ENVOY_PUBLISH_PORT:
        sh: "{{.YQ}} '.dev.envoy_docker.publish_port' /boardsbe/config/dev.yaml"
    cmd: go run github.com/fullstorydev/grpcui/cmd/grpcui@latest -plaintext localhost:{{.ENVOY_PUBLISH_PORT}}
