# section only presented in dev config and not in deployment one
dev:
  envoy_docker:
    publish_port: 2222 # use this port to access API
    docker_port: 3333 # can be any

grpc_server:
  port: 4444
